# Generated by Django 5.0.6 on 2024-06-03 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_bookrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book_isbn',
            name='issused',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book_isbn',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isbns', to='main.book'),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='requests', to='main.book'),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='book_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
