# Generated by Django 5.0.6 on 2024-06-03 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_book_isbn_issused_alter_book_isbn_book_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_isbn',
            old_name='issused',
            new_name='issued',
        ),
    ]
