# Generated by Django 5.0.6 on 2024-06-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_issused_book_isbn_issued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
